name: Deploy Application
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.66.0
          target: wasm32-wasi # WebAssembly target

      - name: Install cargo-nextest
        run: curl -Ls https://get.nexte.st/latest/linux | sudo tar zxf - -C /usr/local/bin

      - name: Install viceroy
        run:  curl -Ls https://github.com/fastly/Viceroy/releases/download/v0.4.2/viceroy_v0.4.2_linux-amd64.tar.gz  | sudo tar zxf - -C /usr/local/bin

      - name: Install wasm-strip
        run: sudo apt install -y wabt

      - name: Run tests
        run: cargo nextest run

      - name: Deploy to Compute@Edge
        uses: fastly/compute-actions@v4
        env:
          FASTLY_API_TOKEN: ${{ secrets.FASTLY_API_TOKEN }}
